[[headers]]
  for = "/*"
  [headers.values]
        Content-Security-Policy = "frame-ancestors 'self' *.vice.com vicetv.com *.vicetv.com *.viceops.net"
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"